WANDB_PROJECT=2024Fall_576 CUDA_VISIBLE_DEVICES=3 python direct_tuning.py \
    --exp-name MELD_roberta_base \
    --dataset MELD \
    --dataset-root ../data \
    --init-lr 3e-6 \
    --max-train-epochs 5 \
    --batch-size 4 \
    --log-dir ./logs \
    --save-args \
    --model roberta-base \
    --experiment-tag roberta_base